name: CI/CD Tests with Real Environment

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium]
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Setup authentication state
      run: |
        if [ -n "${{ secrets.AUTH_STATE_JSON }}" ]; then
          echo "Setting up authentication from secrets..."
          echo '${{ secrets.AUTH_STATE_JSON }}' > auth-state.json
        else
          echo "Warning: No AUTH_STATE_JSON secret found - tests may fail without authentication"
          echo "Please set up GitHub secrets as documented in .github/SECRETS_SETUP.md"
        fi
      
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browser }} --config=playwright.ci.config.ts
      env:
        TEST_BASE_URL: ${{ secrets.TEST_BASE_URL || 'https://azsqsmsls300.amr.corp.intel.com:4012' }}
        QA_BASE_URL: ${{ secrets.QA_BASE_URL || 'https://AZVQSMSWEB360.amr.corp.intel.com:4012' }}
      env:
        CI: true
        MOCK_AUTH: true
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}-ci-pr${{ github.event.number || 'push' }}
        path: playwright-report/
        retention-days: 14
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-ci-pr${{ github.event.number || 'push' }}
        path: test-results/
        retention-days: 14
