name: CI/CD Tests with Mock Auth

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium]
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Create mock authentication state
      run: |
        cat << 'EOF' > auth-state.json
        {
          "cookies": [],
          "origins": [
            {
              "origin": "https://azsqsmsls300.amr.corp.intel.com:4012",
              "localStorage": [
                {
                  "name": "mockAuth",
                  "value": "true"
                }
              ]
            }
          ]
        }
        EOF
        
    - name: Run Playwright tests with mock auth
      run: npx playwright test --project=${{ matrix.browser }} --config=playwright.ci.config.ts
      env:
        CI: true
        MOCK_AUTH: true
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}-ci-pr${{ github.event.number || 'push' }}
        path: playwright-report/
        retention-days: 14
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-ci-pr${{ github.event.number || 'push' }}
        path: test-results/
        retention-days: 14
